# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Squadup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedComments',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_reported', models.DateTimeField(auto_now_add=True)),
                ('time_moderated', models.DateTimeField()),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Squadup.Comment')),
                ('moderated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Squadup.Moderator')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Squadup.User')),
            ],
        ),
        migrations.CreateModel(
            name='ReportedEvents',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_reported', models.DateTimeField(auto_now_add=True)),
                ('time_moderated', models.DateTimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Squadup.Event')),
                ('moderated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Squadup.Moderator')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Squadup.User')),
            ],
        ),
        migrations.AddField(
            model_name='reportedusers',
            name='disabled_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Squadup.Admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportedusers',
            name='time_disabled',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportedusers',
            name='time_moderated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportedusers',
            name='time_reported',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
